sudo: required
services:
  - docker

before_install:
  - docker build -t banabasave/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true banabasave/react-test npm test

after_success:
  - docker build -t banbasave/multi-client ./client
  - docker build -t banbasave/multi-nginx ./nginx
  - docker build -t banbasave/multi-server ./server
  - docker build -t banbasave/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push banbasave/multi-client
  - docker push banbasave/multi-nginx
  - docker push banbasave/multi-server
  - docker push banbasave/multi-worker

